### ISSUE TITLE
object_diff duplicates entries of workflow_job_templates

### ISSUE THREAD

**Issue by dbk-rabel** [redhat-cop/aap_configuration_extended#10]
Hi.

Not sure, if this is a known issue. But it seems, that object_diff cannot handle workflow_job_templates properly.

In our Playbook we always run the roles to create objects, then object_diff and then the other roles again to delete objects.

From the logs with two workflow job templates:

```
TASK [infra.controller_configuration.workflow_job_templates : Managing Workflows] ***
ok: [localhost] => (item=Create/Update Workflow wt_debeka_cifs_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_lun_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_nfs_create)

...

object_diff

...

TASK [infra.controller_configuration.workflow_job_templates : Managing Workflows] ***
ok: [localhost] => (item=Create/Update Workflow wt_debeka_cifs_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_lun_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_nfs_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_cifs_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_lun_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_nfs_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_cifs_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_lun_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_nfs_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_cifs_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_lun_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_nfs_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_cifs_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_lun_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_nfs_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_cifs_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_lun_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_nfs_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_cifs_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_lun_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_nfs_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_cifs_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_lun_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_nfs_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_cifs_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_lun_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_nfs_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_cifs_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_lun_create)
ok: [localhost] => (item=Create/Update Workflow wt_debeka_nfs_create)

```

**Comment by dbk-rabel** [comment]
PS: I know the object_diff role needs refactoring anyways. Just wanted to note that this is also an issue.

**Comment by ivarmu** [comment]
> In our Playbook we always run the roles to create objects, then object_diff and then the other roles again to delete objects.

@dbk-rabel: The workflow is incorrect here... the expeted one for a correct object diff is the following one, as can be seen at https://github.com/redhat-cop/aap_configuration_extended/blob/devel/roles/object_diff/tests/drop_diff.yml:

    - role: infra.controller_configuration.filetree_read
    - role: infra.controller_configuration.object_diff
    - role: infra.controller_configuration.dispatch

Could you check if you get any issue with the expected execution order?

**Comment by dbk-rabel** [comment]
> The workflow is incorrect here...

@ivarmu: We are actually kind of using the workflow you proposed. You can think about it as something like this:

- role: infra.controller_configuration.filetree_read
- role: infra.controller_configuration.dispatch
- role: infra.controller_configuration.object_diff
- role: infra.controller_configuration.dispatch


We found the problem though: We were trying to do the object_diff for each organization individually and concatenate the findings. But we were using the full data from scm each time. We fixed it now.

Thank your anyways!

Yours
  David
